name: Plingdollar
exclude: [etc]
twitter_url: http://twitter.com/willspeak/
flickr_url: http://flickr.com/photos/alphaindigo
url: http://willspeak.me

markdown: kramdown

prose:
  rooturl: "_posts"
  siteurl: "http://willspeak.me/"
  media: "img/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"